version: '3'

services:
  testapi:
    container_name: testapi
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: any
    env_file:
    - ./testapi.env
    networks:
      - iauro
    image: testapi:latest
    ports:
            - '3000:3000'
  mongo:
    image: 'mongo:4'
    restart: unless-stopped
    container_name: mongo
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./docker-data:/data/db
    networks:
      - iauro
  mysqldb:
    image: 'mysql:8.0.28'
    container_name: mysql
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysqldb:/var/lib/mysql
    networks:
      - iauro
networks:
  iauro:
volumes:
  docker-data:
  mysqldb: